# Generated by Django 5.0.3 on 2024-04-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0004_event_end_time_event_start_time_alter_event_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="continuous",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
