# Generated by Django 5.0.3 on 2024-04-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_continuous"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="continuous",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
