# Generated by Django 5.0.3 on 2024-04-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_continuous"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="extra_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
