# Generated by Django 5.0.3 on 2024-05-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_event_extra_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
